TEXDIR /texlive
TEXMFSYSVAR /texlive/texmf-var
TEXMFSYSCONFIG /texlive/texmf-config
TEXMFLOCAL /texlive/texmf-local
TEXMFHOME $TEXMFLOCAL
TEXMFVAR $TEXMFSYSVAR
TEXMFCONFIG $TEXMFSYSCONFIG
instopt_portable 1
